elastic/rally-tracks

geonames/terms.txt, geonames/track.json, geonames/track.py
This adds `terms` queries with 30k terms used in various configurations to the
`geonames` dataset so that we are more likely to know about regressions in the
future.
=> Add `terms` queries to the `geonames` track.

nested/track.json, nested/track.py
Something to compare against to see if optimizations that will be added via elastic/elasticsearch#23917 actually help.
=> Add inner hits to nested track

geonames/challenges/default.json, geonames/operations/default.json
Add benchmarks to compare new script_score query with function_score query
=> Benchmarks to compare scripting queries

geonames/challenges/default.json, http_logs/challenges/default.json, nested/challenges/default.json, noaa/challenges/default.json, nyc_taxis/challenges/default.json, pmc/challenges/default.json
Updating target-throughput for some benchmarks to achieve more stable
latency scores.
=> Update target throughput

http_logs/operations/default.json, metricbeat/operations/default.json, nyc_taxis/operations/default.json
Bad parameters in previous PR threw off our benchmarks.  Addressed as per comments on #85
=> Fix bad intervals

nyc_taxis/challenges/default.json, nyc_taxis/operations/default.json
This'll be useful for comparing the performance of `auto_date_histogram`
with `date_histogram` and for comparing `auto_date_histogram` under some
new optimization that I'm working on.
=> Add metrics to date-histogram

noaa/challenges/default.json, noaa/operations/default.json
Performance tests for elastic/elasticsearch#57483
=> Add operations for geohash and geotile aggs

nyc_taxis/challenges/default.json, nyc_taxis/operations/default.json
Iterates a bit on the date_histogram metrics, filtering "bad" data and increasing the throughput targets accordingly.
=> Iterate on date_histogram metrics

noaa/challenges/default.json
Addresses issues on high throughput per https://github.com/elastic/night-rally/issues/321#issuecomment-708468602
=> Reduce range_field_big_range from 8 to 6 throughput

eql/README.md, eql/endgame-4.28.2-000001.json, eql/track.json, eql/track.py
Add a new track to benchmark EQL performance.
=> Add EQL track

noaa/challenges/default.json, noaa/operations/default.json
Adds operations to the challenge I've been using to test aggregation
performance that test the performance of the terms aggregation alone
without any child aggregations.
=> Add operation for terms agg alone

noaa/challenges/default.json, noaa/operations/default.json
This should tell us if #69806 is doing sensible things.
=> Add operations for terms with sub-aggs

http_logs/index-runtime-fields.json
I made a copy-and-paste error which broke all non-grok fields. I guess I
didn't test well enough. I'm sorry!
=> Fix error in field name

http_logs/track.py
This time it was index-of that didn't work.....
=> Fix another error in field names in runtime fields benchmark

noaa/challenges/default.json, noaa/operations/default.json
Tests for the speed cost of implementing
https://github.com/elastic/elasticsearch/pull/70579
=> Add benchmark for top_metrics fetching keyword

http_logs/track.py
Reverts elastic/rally-tracks#171.  see https://github.com/elastic/rally-tracks/pull/171#issuecomment-828598581
=> Revert "update to use new on_prepare_track API"

eql/README.md, eql/track.json, eventdata/README.md, eventdata/challenges/default.json, geonames/README.md, geonames/challenges/default.json, geopoint/README.md, geopoint/challenges/default.json, geopointshape/README.md, geopointshape/challenges/default.json, geoshape/README.md, geoshape/challenges/default.json, http_logs/README.md, http_logs/challenges/default.json, metricbeat/challenges/default.json, nested/README.md, nested/challenges/default.json, noaa/README.md, noaa/challenges/default.json, nyc_taxis/README.md, nyc_taxis/challenges/default.json, percolator/README.md, percolator/challenges/default.json, pmc/README.md, pmc/challenges/default.json, so/README.md, so/challenges/default.json
Parameter cannot be hyphenated
=> Fix bug in "ignore-response-error-level" parameter

http_logs/index.json
Relates to https://github.com/elastic/rally-tracks/issues/170
Relates to elastic/ecs#1396
=> Migrate text field to match_only_text

nyc_taxis/challenges/indexing-querying.json
With this, we add a concurrent indexing/querying challenge to NYC Taxis.
=> Nyc concurrent challenge

eql/README.md, eql/track.json
Additional challenges. See `eql/README.md` for more explanations about the query selection and parametrization.
=> Additional challenges for EQL track

eql/README.md, eql/track.json
- Additional challenges for EQL track (#210)
=> [7.12] Additional challenges for EQL track (#210)

eql/README.md, eql/track.json
- Additional challenges for EQL track (#210)
=> [7.14] Additional challenges for EQL track (#210)

eql/track.py, noaa/challenges/sql.json, noaa/track.py
=> [7.12] SQL benchmarks (#216)

eql/track.py, noaa/challenges/sql.json, noaa/track.py
=> [7.14] SQL benchmarks (#216)

nyc_taxis/challenges/indexing-querying.json, nyc_taxis/operations/default.json
Reverts elastic/rally-tracks#241
=> Revert "correct field name in nyc_taxis"

geoshape/challenges/default.json, geoshape/files.txt, geoshape/index.json, geoshape/operations/default.json, geoshape/track.json
Makes this track to run under 1.5 hours.
backport #238
=> Add new geoshape default track that runs with less data (#238)

dense_vector/challenges/default.json
This gives us insights into search performance of
unmerged indices, which we expect to be common
use case for most users.
=> Dense vectors add searches before force merge

elastic/Makefile
As was done in Rally and esbench already.
=> Allow running `make` commands from active virtualenv

elastic/logs/challenges/logging-querying.json, elastic/logs/challenges/logging-snapshot-mount.json, elastic/logs/track.json, elastic/logs/track.py, elastic/shared/runners/snapshot.py, elastic/tests/runners/snapshot_test.py
#302 but on the master branch.
=> Support frozen tier logging benchmarks

.pre-commit-config.yaml, Makefile, dense_vector/_tools/parse.py, elastic/security/parameter_sources/events_emitter.py, elastic/shared/parameter_sources/datastream.py, elastic/shared/parameter_sources/processed.py, elastic/shared/runners/datastream.py, elastic/shared/runners/remote_cluster.py, elastic/shared/track_processors/data_generator.py, elastic/shared/utils/time.py, elastic/tests/parameter_sources/__init__.py, elastic/tests/parameter_sources/template_test.py, elastic/tests/runners/remote_cluster_test.py, geonames/track.py, nested/track.py
We need to install black in the developer virtual environment to allow
editors to use it. And there are various places where the formatting
could be improved.
=> Finish black migration

elastic/logs/challenges/many-shards-snapshots.json
Unfortunately it's not this simple...
=> Revert "Make base_path static"

elastic/it/query-tests/discover.json, elastic/logs/challenges/logging-disk-usage.json, elastic/logs/pipelines/logs-k8-app.json, elastic/logs/templates/composable/logs-k8-application.log.json, elastic/logs/track.json, elastic/tests/runners/datastream_test.py, elastic/tests/runners/resources/data_streams/logs.json
This reverts commit b4849a3548d702d39537319c9a3ab8a2b3520371.
=> Revert "Remove legacy application-logs corpora (#335)"

geopoint/challenges/default.json, geopoint/operations/default.json, geopointshape/challenges/default.json, geopointshape/operations/default.json, geoshape/challenges/default.json, geoshape/index.json, geoshape/operations/default.json
Each of the set of three covers:
* geohash - tile the plane with geohash
* geotile - tile the plane with MVT-like tiles
* geohex - tile the plan with H3 hexagons (and pentagons)
=> Added six geo benchmarks, three geo_grid and three grid aggregations

nyc_taxis/challenges/default.json, nyc_taxis/operations/default.json
Add benchmarks comparing `date_histogram` aggregation with a stats by date field in ESQL
=> Add benchmarks for `date_histogram` 

nyc_taxis/operations/default.json
=> Fix date format for ESQL queries

elastic/logs/README.md
Adds some docs explaining these previously undocumented challenges.
=> Add CCS/CCR challenge to elastic/logs README

.github/workflows/ci.yml
This PR adds Slack notifications on scheduled runs and on pushes to `master` branch.
=> Add GitHub Actions Slack notifications

k8s_metrics/README.md
Fix minor typos in the k8s_metrics README.
=> k8s_metrics README.md typos

elastic/security/README.md
Add a few links to external sources and places in source code.
=> Update README for elastic/security

.github/workflows/ci.yml
See https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
=> Add ES logs to CI workflow artifact in GitHub

k8s_metrics/README.md, k8s_metrics/challenges/default.json, k8s_metrics/operations/default.json
* Fast refresh parameter update for search after write.
* Update fast-refresh docs with new parameter values.
=> k8s_metrics: update fast-refresh indexing parameters

.buildkite/it/pipeline.yml, catalog-info.yaml
Create empty buildkite workflow
=> Add dummy buildkite pipeline

nyc_taxis/operations/default.json
Swap arguments to date_trunc() after [upstream changes](https://github.com/elastic/elasticsearch/pull/98624).
=> ESQL: Swap date_trunc() arguments

.github/workflows/ci.yml
An attempt to catch problems such as https://github.com/elastic/rally-tracks/pull/461.
=> Modify Python versions used in GitHub actions

elser-ingest-speedtest/README.md, elser-ingest-speedtest/challenges/ELSER-V1.json, elser-ingest-speedtest/challenges/ELSER-V2-PlatformSpecific.json, elser-ingest-speedtest/challenges/ELSER-V2.json, elser-ingest-speedtest/challenges/ESLER-V2-PlatformSpecific.json, elser-ingest-speedtest/track.py
New benchmarks for the new models introduced in 8.11.
=> Added ELSER V2 challenges for the elser-ingest-speedtest track

.github/workflows/sync-latest-branch.yml
Changes most recent branch from 8.7 to 8.11. Related to https://github.com/elastic/rally-tracks/issues/474.
=> Update sync workflow

pmc/README.md, pmc/challenges/default.json, pmc/challenges/indexing-querying.json, pmc/index.json
=> Unblock pmc for public serverless

geopoint/README.md, geopoint/challenges/default.json, geopoint/index.json, geopointshape/README.md, geopointshape/challenges/default.json, geopointshape/index.json, geoshape/README.md, geoshape/challenges/default.json, geoshape/index.json
=> Unblock geo tracks for public serverless

nested/README.md, nested/challenges/default.json, nested/index.json, noaa/README.md, noaa/challenges/default.json, noaa/index.json
=> Unblock nested and noaa for public serverless

nyc_taxis/README.md, nyc_taxis/challenges/common/autoscale-schedule.json, nyc_taxis/challenges/common/update-aggs-only-schedule.json, nyc_taxis/challenges/default.json, nyc_taxis/index-payment-types.json, nyc_taxis/index-rate-codes.json, nyc_taxis/index-trip-types.json, nyc_taxis/index-vendors.json, nyc_taxis/index.json
=> Unblock nyc_taxis for public serverless

nyc_taxis/challenges/default.json, nyc_taxis/operations/default.json
This is to compare ESQL to plan terms agg
=> Added new simple count(*) query and search equivalent to NYC Taxis

it/test_all_tracks_and_challenges.py
A temporary measure due to frequent ELSER IT test failures.
=> Disable ELSER in IT tests

elastic/logs/challenges/logging-querying.json, elastic/logs/operations/esql.json
So we can compare performance between _search and ESQL for these cases.
=> Added _search versions of the ESQL count(*) queries

tsdb/README.md, tsdb/challenges/default.json
Useful if users would like to apply extra load.
=> Add new `search_clients` track parameter to TSDB track

openai_vector/README.md, openai_vector/_tools/parse_documents.py, openai_vector/_tools/parse_queries.py, openai_vector/_tools/requirements.txt, openai_vector/challenges/default.json, openai_vector/files.txt, openai_vector/index-vectors-only-mapping.json, openai_vector/index-vectors-with-text-mapping.json, openai_vector/operations/default.json, openai_vector/track.json, openai_vector/track.py
Add a rally track for OpenAI vector benchmarking. Based on the `cohere_vector` track.
SEARCH-84
=> OpenAI Vector Rally Track

cohere_vector/README.md
The documented track parameters for the cohere_vector track are incorrect.
In this PR:
* Align documented track parameter names with the track
* Remove unused parameters
=> Update cohere_vector track README

elastic/logs/challenges/many-shards-quantitative.json, elastic/logs/tasks/field-caps-index-filter-empty-fields.json, elastic/logs/tasks/field-caps-index-filter.json
Added two more tasks to benchmark field_caps requests with index-filter for both standard and non-empty field requests.
=> Tasks for benchmarking field_caps with index-filter

elastic/apm/index-template.json, elastic/apm/tasks/setup.json, elastic/apm/track.json
Addresses https://github.com/elastic/rally-tracks/pull/550/commits/5c8d4fe310a050adf4d2acd2fbf7cde21e3cbc0f#r1500196363
=> elastic/apm: do not update/use `apm@settings` template

nyc_taxis/operations/default.json
=> [ES-8028] Make the [pragma] for esql segment partitioning only happen on stateful

elastic/logs/challenges/categorize-text.json
Adds a challenge for the `caegorize-text` aggregation, something for which we're keen to keep an eye on performance.
=> Add a categorize-text challenge to the elastic/logs track.

.github/workflows/ci.yml
Due to https://github.com/actions/setup-python/issues/850.
=> Pin MacOS version at 13

it_serverless/conftest.py, it_serverless/test_logs.py, it_serverless/test_selected_tracks_and_challenges.py, tsdb/README.md, tsdb/challenges/default.json, tsdb/operations/default.json
=> Add a new `low-latency` challenge to `tsdb` track (#595)

elastic/logs/README.md, elastic/logs/challenges/categorize-text.json
* bulk import index data
* target only those indices that have the required `message` field
* remove code duplication in the challenge definition
=> Improvements to the categorize-text challenge

tsdb/challenges/default.json, tsdb/operations/default.json
=> Backport: Use a pipeline to generate doc id and use correct doc id values

geopoint/challenges/default.json, geopoint/operations/default.json
This is in preparation for benchmarking against ES|QL
=> Updated geopoint distance queries including sort, filter and aggs

elser-ingest-speedtest/bert-vocab-whole-words-mapping.json
excludes is not available in serverless, thus index creation currently fails. This excludes the excludes on serverless
=> Make exclude conditional on not serverless

wikipedia/challenges/default.json, wikipedia/operations/default.json, wikipedia/track.py
Adds some tests for query rules of various sizes to the Wikipedia track.
=> Add query rule tests to the wikipedia track

elastic/security/templates/component/track-shared-logsdb-mode.json, elastic/security/templates/composable/.logs-endpoint.action.responses.json, elastic/security/templates/composable/.logs-endpoint.actions.json, elastic/security/templates/composable/.logs-endpoint.diagnostic.collection.json, elastic/security/templates/composable/logs-endpoint.alerts.json, elastic/security/templates/composable/logs-endpoint.events.file.json, elastic/security/templates/composable/logs-endpoint.events.library.json, elastic/security/templates/composable/logs-endpoint.events.network.json, elastic/security/templates/composable/logs-endpoint.events.process.json, elastic/security/templates/composable/logs-endpoint.events.registry.json, elastic/security/templates/composable/logs-endpoint.events.security.json, elastic/security/templates/composable/security-auditbeat.json, elastic/security/templates/composable/security-filebeat.json, elastic/security/templates/composable/security-metricbeat.json, elastic/security/templates/composable/security-packetbeat.json, elastic/security/templates/composable/security-winlogbeat.json, elastic/security/track.json
This is a backport of #640 to branch `8.15`.
=> Introduce an `index_mode` param into the `elastic/security` Rally track

elastic/logs/track.json
This is a backport of #642 to branch 8.15
=> Allow skipping delete of fleet component template

elastic/security/templates/component/logs-endpoint.events.file@package.json, elastic/security/templates/component/logs-endpoint.events.file@settings.json, elastic/security/templates/component/logs-endpoint.events.library@package.json, elastic/security/templates/component/logs-endpoint.events.library@settings.json, elastic/security/templates/component/logs-endpoint.events.network@package.json, elastic/security/templates/component/logs-endpoint.events.network@settings.json, elastic/security/templates/component/logs-endpoint.events.process@package.json, elastic/security/templates/component/logs-endpoint.events.process@settings.json, elastic/security/templates/component/logs-endpoint.events.registry@package.json, elastic/security/templates/component/logs-endpoint.events.registry@settings.json, elastic/security/templates/component/logs-endpoint.events.security@package.json, elastic/security/templates/component/logs-endpoint.events.security@settings.json
This is a backport of #647 to 8.15
=> Disallow usage of ilm lifecycle for serverless

elastic/security/templates/composable/security-auditbeat.json, elastic/security/templates/composable/security-filebeat.json, elastic/security/templates/composable/security-metricbeat.json, elastic/security/templates/composable/security-packetbeat.json, elastic/security/templates/composable/security-winlogbeat.json
This is a backport of #650 to 8.15.
=> Prevent usage of ilm lifecycle in serverless

.github/workflows/ci.yml
=> Backport #660 to 8.15

elastic/security/README.md, elastic/security/challenges/security-indexing-querying.json
=> Include ability to force merge segments in `elastic/security`

.github/workflows/ci.yml
=> Backport #660 to 8.14

.gitignore
Copied from https://github.com/elastic/rally/blob/0e77d12ebafb47a64ea2996db4eec23f05ee800a/.gitignore#L117-L121
=> Ignore VSCode files

tsdb/challenges/default.json
Follow up from elastic/elasticsearch-benchmarks#2281
=> Use polling mode for force merge in tsdb track

noaa/aggs-tasks.json, noaa/operations/default.json
This adds a test for super deeply nested terms aggs
=> Deep terms agg

nyc_taxis/index.json, tsdb/index-template.json, tsdb/index.json
These were not updated in #732 as the setting was not available in serverless.
=> Restore the source mode setting in the remaining tests

.github/workflows/ci.yml
(cherry picked from commit 68fb7d457d44700ae1e58e8cef7b5bab6416863c)
=> Bump action versions (#724)

wikipedia/README.md, wikipedia/track.py
Set the request cache default to false for the Wikipedia track.
=> [Wikipedia] Disable the request cache by default

nyc_taxis/operations/default.json
Forward-port from https://github.com/elastic/rally-tracks/pull/812.
=> Accept pragma risks in ESQL challenge in NYC Taxis

catalog-info.yaml
Follow-up to https://github.com/elastic/rally-tracks/pull/809.
=> Remove unnecessary dependency

.buildkite/it/pipeline.yml, .buildkite/pull-requests.json, catalog-info.yaml
This will backport the following commits from `master` to `8.15`:
- [Trim unnecessary ITs (#809)](https://github.com/elastic/rally-tracks/pull/809)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [8.15] Trim unnecessary ITs (#809)

elastic/logs/challenges/logging-querying.json, elastic/logs/tasks/index-setup.json, noaa/challenges/default.json, so/challenges/default.json, tsdb/challenges/default.json
Introduces `setup`, `index` and `health` tags for easier task inclusion/exclusion.
=> [ES-12320] Align tags in Logs, NOAA, SO and TSDB

wikipedia/README.md
This will backport the following commits from `master` to `8.15`:
- [Update README.md (#604)](https://github.com/elastic/rally-tracks/pull/604)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> [8.15] Update README.md (#604)

joins/_tools/lookup_idx_string_int.sh, joins/challenges/default.json, joins/challenges/large.json, joins/challenges/nightly.json, joins/challenges/small.json, joins/index-lookup_idx_1000_100000_200000_f10.json, joins/operations/default.json, joins/track.json
Adding some queries for joins on multiple keys
=> ES|QL: Add queries for LOOKUP JOIN with multiple join keys
